apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app.kubernetes.io/name: kube-news
    app.kubernetes.io/component: app
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kube-news
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 8080
      targetPort: http
